# Copyright (c) 2016-2020 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: A Primer for Earth Engine
site_url: https://github.com/jeffhowarth/eeprimer
site_author: Jeff Howarth
site_description: >-
  A lesson collection for raster GIS and image processing
  with Google Earth Engine. Introductory, undergraduate level.

# Repository
repo_name: jeffhowarth/eeprimer
repo_url: https://github.com/jeffhowarth/eeprimer
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020 Jeff Howarth

# Configuration
theme:
  name: material
  #custom_dir: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - tabs
    #- instant
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo
  favicon: assets/favicon.png

# Plugins
plugins:
  - search
  - minify

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jeffhowarth
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jeffgeographer

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
      title: 'Task List'
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # - pymdownx.highlight:
  #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - How I organized this primer:
    - Introduction: index.md
    - Audience: intro/02-audience.md
    - Problem Based Lessons: intro/03-problem-based-lessons.md
    - Conceptual Foundations: intro/04-conceptual-foundations.md
    - Learning Assessments: intro/05-learning-assessments.md
  - Getting started:
    - Introduction: start/intro.md
    - Google Earth Engine:
      - Get an account: start/gee/01-sign-up.md
      - Start Code Editor: start/gee/02-start-code-editor.md
      - Navigate Code Editor: start/gee/03-navigate-code-editor.md
      - Set up home repo: start/gee/04-create-repo.md
  - Problem-Based Lessons:
    - Contents: pbl/index.md
    - Lesson 1:
      - Hello, Base Map!: pbl/01/intro.md
      - Problem and plan: pbl/01/problem.md
      - Implement plan with code: pbl/01/implement.md
      - Foundational concepts: pbl/01/foundations.md
      - Test your understanding: pbl/01/learning.md
    - Lesson 2:
      - Outline: pbl/02/01-outline.md
  - Conceptual Foundations:
    - Index: concepts/index.md
    - Coordinate Reference System: concepts/crs.md
    - Map Center: concepts/mapCenter.md
    - Map Scale: concepts/mapScale.md
    - Zoom Level: concepts/zoomLevel.md
  - Learning Assessments:
    - Outline: assessments/index.md







#  - Contributing: contributing.md
#  - License: license.md

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
