# Copyright (c) 2016-2020 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: A Primer for Google Earth Engine
site_url: https://github.com/jeffhowarth/eeprimer
site_author: Jeff Howarth
site_description: >-
  A lesson collection for raster GIS and image processing
  with Google Earth Engine. Introductory, undergraduate level.

# Repository
repo_name: jeffhowarth/eeprimer
repo_url: https://github.com/jeffhowarth/eeprimer
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020 Jeff Howarth

# Configuration
theme:
  name: material
  #custom_dir: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - tabs
    #- instant
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo
  favicon: assets/favicon.png

# Plugins
plugins:
  - search
  - minify

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jeffhowarth
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jeffgeographer

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # - pymdownx.highlight:
  #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - How I organized this primer:
    - Introduction: index.md
    - Audience: projects/intro/02-audience.md
    - Chapters: projects/intro/03-chapters.md
    - Worked-out problems: projects/intro/04-worked-out-problems.md
    - Independent problems: projects/intro/05-independent-problems.md
  - Getting Started:
    - Get an account: projects/getting-started/01-sign-up.md
    - Start Code Editor: projects/getting-started/02-start-code-editor.md
    - Navigate Code Editor: projects/getting-started/03-navigate-code-editor.md
    - Set up home repo: projects/getting-started/04-create-repo.md
  - Cartographic Foundations:
    - Introduction: projects/cart/01-overview/01-introduction.md
    - Hello, Base Map!:
      - Objectives: projects/cart/02-base-map/01-objectives.md
      - Change the base map: projects/cart/02-base-map/02-change-base-map.md
      - Inspect properties of a location: projects/cart/02-base-map/03-inspect-location.md
      - Understand coordinate reference systems: projects/cart/02-base-map/04-crs.md
      - Understand zoom level: projects/cart/02-base-map/05-zoom.md
      - Understand scale: projects/cart/02-base-map/06-scale.md
      - Change map center: projects/cart/02-base-map/07-map-center.md
    - Geometry and Features:
      - Objectives: projects/jhLessons/jh0102.md
      - Draw a point: projects/cart/03-geometry-features/01-draw-point.md
      - Make a feature: projects/cart/03-geometry-features/02-make-feature.md
      - Add a property: projects/cart/03-geometry-features/03-add-property.md
      - Get a property: projects/cart/03-geometry-features/04-get-property.md
    - Feature Collections:
      - Objectives: projects/jhLessons/jh0103.md
      - Feature Collections: projects/cart/04-feature-collections/01-feature-collections.md
      - Print geometry: projects/cart/04-feature-collections/02-print-geometries.md
      - Create a feature collection: projects/cart/04-feature-collections/03-create-feature-collection.md
      - Create a line feature: projects/cart/04-feature-collections/04-create-line-feature.md
      - Add feature layer to map: projects/cart/04-feature-collections/05-add-feature-layer-to-map.md
    - Applying Methods:
      - Objectives: projects/jhLessons/jh0104.md
      - Buffer a feature: projects/cart/05-apply-methods/01-buffer-feature.md
      - Buffer a feature collection problem: projects/cart/05-apply-methods/02-feature-collection-buffer-problem.md
      - Create a function: projects/cart/05-apply-methods/03-create-a-function.md
      - Map function over collection: projects/cart/05-apply-methods/04-map-function-over-collection.md
  - Raster Foundations:
    - Outline: projects/raster/01-outline.md
  - Remote Sensing Foundations:
    - Outline: projects/rs/01-intro.md
  - Independent Problems:
    - Cartographic: projects/ip/cart/outline.md
    - Raster: projects/ip/raster/outline.md
    - Remote Sensing: projects/ip/rs/outline.md



#  - Contributing: contributing.md
#  - License: license.md

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
